<a href="https://colab.research.google.com/github/JHJ4012/tensorflow_studying/blob/master/multi_variable_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

# 일일히 다 짤 경우
# x1_data = [73.,93.,89.,96.,73.]
# x2_data = [80.,88.,91.,98.,66.]
# x3_data = [75.,93.,90.,100.,70.]
# y_data = [152.,185.,180.,196.,142.]

# x1 = tf.placeholder(tf.float32)
# x2 = tf.placeholder(tf.float32)
# x3 = tf.placeholder(tf.float32)

# Y = tf.placeholder(tf.float32)

# w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
# w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
# w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
# b = tf.Variable(tf.random_normal([1]), name = 'bias')

# hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost = tf.reduce_mean(tf.square(hypothesis - Y))
# optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
# train = optimizer.minimize(cost)

# sess = tf.Session()
# sess.run(tf.global_variables_initializer())

# for step in range(2001):
#   cost_val, hy_val,_ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2 : x2_data, x3: x3_data, Y : y_data})

#   if step % 10 == 0:
#     print(step, "Cost : " , cost_val, "\nPrediction: \n", hy_val)


#매트릭스 사용
x_data = [[73.,80.,75.], [93.,88.,93.], [89.,91.,90.],[96.,98.,100.], [73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) #데이터 n개 가질 것이다를 tensorflow에서 None으로 씀
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#matmul은 행렬 곱을 해주는 메서드
hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val,_ = sess.run([cost, hypothesis, train], feed_dict={X : x_data, Y : y_data})

  if step % 10 == 0:
    print(step, "Cost : " , cost_val, "\nPrediction: \n", hy_val)

#Ask my score
print("Your score will be " , sess.run(hypothesis, feed_dict = {X: [[100,70,101]]}))
print("Other scores will be" , sess.run(hypothesis, feed_dict = {X : [[60,70,110], [90,100,80]]}))

0 Cost :  9274.552 
Prediction: 
 [[63.770912]
 [83.482704]
 [78.871864]
 [85.685326]
 [65.27714 ]]
10 Cost :  2.4250016 
Prediction: 
 [[148.95833]
 [185.8609 ]
 [179.75243]
 [195.541  ]
 [143.36386]]
20 Cost :  2.3287804 
Prediction: 
 [[149.22173]
 [186.1668 ]
 [180.05939]
 [195.87454]
 [143.59512]]
30 Cost :  2.3174942 
Prediction: 
 [[149.22816]
 [186.16385]
 [180.06207]
 [195.87672]
 [143.59085]]
40 Cost :  2.3062797 
Prediction: 
 [[149.23381]
 [186.16   ]
 [180.06381]
 [195.8779 ]
 [143.58588]]
50 Cost :  2.2951374 
Prediction: 
 [[149.23941]
 [186.15616]
 [180.06554]
 [195.87904]
 [143.58089]]
60 Cost :  2.2840426 
Prediction: 
 [[149.24506]
 [186.15236]
 [180.0673 ]
 [195.88023]
 [143.57597]]
70 Cost :  2.2729893 
Prediction: 
 [[149.25063]
 [186.14848]
 [180.06898]
 [195.88136]
 [143.571  ]]
80 Cost :  2.262022 
Prediction: 
 [[149.25621]
 [186.14468]
 [180.07072]
 [195.88252]
 [143.56609]]
90 Cost :  2.2511086 
Prediction: 
 [[149.26176]
 [186.14088]
 [180.07243]
 [195.8836