<a href="https://colab.research.google.com/github/JHJ4012/tensorflow_studying/blob/master/train_and_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

x_data = [[1,2,1], [1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1], [0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost) #learning rate을 조종해가며 learning rate에 따라 어떻게 결과가 달라지는지 확인해보기
                                                                                  #learning rate을 너무 크게 하면 NaN 뜰 수 있음
                                                                                  #learning rate을 너무 작게 하면 cost가 계속 같을 수 있다.

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict= {X:x_data ,Y:y_data})
    print(step, cost_val, W_val)
  print("Prediction", sess.run(prediction, feed_dict={X:x_test}))
  print("Accuracy", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 2.0373523 [[ 1.9862288   1.9746644   0.35784927]
 [-0.03108077  0.00839578 -0.6359745 ]
 [-0.50439334 -0.7755675  -1.2311672 ]]
1 1.7436643 [[ 1.963633    1.9605339   0.39457574]
 [-0.09127396 -0.02960435 -0.5377812 ]
 [-0.5707234  -0.79537845 -1.1450262 ]]
2 1.4675753 [[ 1.9489621   1.9392176   0.43056288]
 [-0.11162034 -0.10548354 -0.44155562]
 [-0.5968316  -0.8535666  -1.0607299 ]]
3 1.2338359 [[ 1.9255083   1.9284568   0.46477744]
 [-0.17918997 -0.12878385 -0.3506857 ]
 [-0.66906667 -0.8603007  -0.9817607 ]]
4 1.0944628 [[ 1.9154104   1.9081756   0.4951565 ]
 [-0.17971201 -0.2049014  -0.2740461 ]
 [-0.67379004 -0.91981673 -0.91752136]]
5 1.0595589 [[ 1.8960961   1.9053891   0.51725733]
 [-0.2309778  -0.19453783 -0.23314384]
 [-0.72776    -0.89418393 -0.88918424]]
6 1.0470906 [[ 1.8929733   1.8934468   0.5323224 ]
 [-0.19835934 -0.23326702 -0.22703311]
 [-0.6980557  -0.91765463 -0.89541787]]
7 1.0361636 [[ 1.8797526   1.8928353   0.5461546 ]
 [-0.2190944  -0.21388403 -0.22568105]
